Repository Team-Sopetit/Sopetit-Android, pull requests merged in 2024-03, with the labels that each got.

#165 #164[hotfix] firebase crashlytics 연동
  app/build.gradle.kts
  build.gradle.kts
Labels: hotfix🚨, Pull Request, 강희🐬

#167 #166 [ui] 카드 기기대응 DimensionRatio 적용
  app/src/main/res/layout/fragment_happy_delete.xml
  app/src/main/res/layout/fragment_happy_my_routine.xml
  app/src/main/res/layout/fragment_happy_routine.xml
Labels: UI, 호연🐻‍❄️

#168 #163 리프레시 토큰 이슈
  app/build.gradle.kts
  app/src/main/java/com/sopetit/softie/di/RetrofitModule.kt
Labels: hotfix🚨, 강희🐬

#170 #169 [hotfix] 토큰 재발급 이슈
  app/build.gradle.kts
  app/src/main/java/com/sopetit/softie/di/RetrofitModule.kt
  app/src/main/java/com/sopetit/softie/ui/login/LoginViewModel.kt
Labels: hotfix🚨, Pull Request, 강희🐬
