Repository Team-Sopetit/Sopetit-Android, pull requests merged in 2024-01, with the labels that each got.

#3 #1 [initial] 프로젝트 기초세팅
  .gitignore
  app/.gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/androidTest/java/com/sopetit/softie/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopetit/softie/SoftieApplication.kt
  app/src/main/java/com/sopetit/softie/data/entity/BaseResponse.kt
  app/src/main/java/com/sopetit/softie/data/entity/NoResponse.kt
  app/src/main/java/com/sopetit/softie/data/entity/SampleEntity.kt
  app/src/main/java/com/sopetit/softie/data/entity/request/SampleRequest.kt
  app/src/main/java/com/sopetit/softie/data/entity/response/SampleResponse.kt
  app/src/main/java/com/sopetit/softie/data/repositoryImpl/SampleRepositoryImpl.kt
  app/src/main/java/com/sopetit/softie/data/service/SampleService.kt
  app/src/main/java/com/sopetit/softie/data/source/SampleDataSource.kt
  app/src/main/java/com/sopetit/softie/di/SampleModule.kt
  app/src/main/java/com/sopetit/softie/domain/entity/Sample.kt
  app/src/main/java/com/sopetit/softie/domain/repository/SampleRepository.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/PostLoginUseCase.kt
  app/src/main/java/com/sopetit/softie/ui/main/MainActivity.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SampleActivity.kt
  app/src/main/java/com/sopetit/softie/util/Context.kt
  app/src/main/java/com/sopetit/softie/util/ItemDiffCallback.kt
  app/src/main/java/com/sopetit/softie/util/binding/BindingActivity.kt
  app/src/main/java/com/sopetit/softie/util/binding/BindingAdapter.kt
  app/src/main/java/com/sopetit/softie/util/binding/BindingFragment.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/sopetit/softie/ExampleUnitTest.kt
  build.gradle.kts
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
Labels: Setting, Pull Request, 강희🐬

#12 #7 [ui] 온보딩 - 테마 선택 뷰
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopetit/softie/domain/entity/Theme.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/BearChoiceFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/SetBearNameFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/themechoice/ChoiceThemeAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/themechoice/ChoiceThemeFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/themechoice/ChoiceThemeViewModel.kt
  app/src/main/res/drawable/ic_doll_face_1.xml
  app/src/main/res/drawable/ic_theme_1.xml
  app/src/main/res/drawable/selector_onboarding_top.xml
  app/src/main/res/drawable/shape_gray100_fill_99_rect.xml
  app/src/main/res/drawable/shape_gray100_filll_100_circle.xml
  app/src/main/res/drawable/shape_main1_fill_99_rect.xml
  app/src/main/res/drawable/shape_white_fill_100_circle.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_onboarding_choice_bear.xml
  app/src/main/res/layout/fragment_onboarding_choice_routine.xml
  app/src/main/res/layout/fragment_onboarding_choice_theme.xml
  app/src/main/res/layout/fragment_onboarding_set_bear_name.xml
  app/src/main/res/layout/item_onboarding_choice_theme.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: UI, 민정🦊

#14 #11 [ui] 스토리텔링 뷰 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopetit/softie/ui/main/happy/HappyEmptyFragment.kt
  app/src/main/java/com/sopetit/softie/ui/storytelling/StoryTellingActivity.kt
  app/src/main/java/com/sopetit/softie/ui/storytelling/StoryTellingConclusionFragment.kt
  app/src/main/java/com/sopetit/softie/ui/storytelling/StoryTellingIntroFragment.kt
  app/src/main/java/com/sopetit/softie/ui/storytelling/StoryTellingMainFragment.kt
  app/src/main/res/drawable/ic_box_closed.xml
  app/src/main/res/drawable/ic_door.png
  app/src/main/res/drawable/ic_girl1.png
  app/src/main/res/drawable/ic_girl2.png
  app/src/main/res/drawable/ic_onboard_next.xml
  app/src/main/res/drawable/ic_spotlight2.xml
  app/src/main/res/drawable/ic_spotlight3.xml
  app/src/main/res/drawable/shape_white_fill_12_rect.xml
  app/src/main/res/layout/activity_story_telling.xml
  app/src/main/res/layout/fragment_story_telling_conclusion.xml
  app/src/main/res/layout/fragment_story_telling_intro.xml
  app/src/main/res/layout/fragment_story_telling_main.xml
  app/src/main/res/values/appearance.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: UI, Pull Request, 강희🐬

#16 #13 [feat] 온보딩 테마 선택 뷰
  app/src/main/java/com/sopetit/softie/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/themechoice/ChoiceThemeAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/themechoice/ChoiceThemeFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/themechoice/ChoiceThemeViewModel.kt
  app/src/main/res/drawable/shape_gray200_fill_12_rect.xml
  app/src/main/res/drawable/shape_main1_fill_12_rect.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_onboarding_choice_theme.xml
  app/src/main/res/layout/item_onboarding_choice_theme.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request, Feat, 민정🦊

#21 #15 [UI] 애착인형 선택뷰
  app/src/main/java/com/sopetit/softie/ui/onboarding/BearChoiceFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearselection/BearSelectionFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearselection/BearSelectionViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/storytelling/StoryTellingConclusionFragment.kt
  app/src/main/res/drawable/ic_bear_brown_down.png
  app/src/main/res/drawable/ic_bear_brown_up.png
  app/src/main/res/drawable/ic_bear_gray_down.png
  app/src/main/res/drawable/ic_bear_gray_up.png
  app/src/main/res/drawable/ic_bear_panda_down.png
  app/src/main/res/drawable/ic_bear_panda_up.png
  app/src/main/res/drawable/ic_bear_red_down.png
  app/src/main/res/drawable/ic_bear_red_up.png
  app/src/main/res/drawable/shape_white_fill_gray000_stroke_radius_20.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_happy_empty.xml
  app/src/main/res/layout/fragment_onboarding_bear_selection.xml
  app/src/main/res/layout/fragment_onboarding_choice_bear.xml
  app/src/main/res/values/strings.xml
Labels: UI, Pull Request, 강희🐬

#26 #17 [feat] 온보딩 루틴 선택 뷰
  app/src/main/java/com/sopetit/softie/domain/entity/Routine.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/themechoice/ChoiceThemeAdapter.kt
  app/src/main/res/drawable/ic_scrollbar.xml
  app/src/main/res/drawable/shape_gray100_fill_12_rect.xml
  app/src/main/res/drawable/shape_gray100_fill_gray400_stroke_100_circle.xml
  app/src/main/res/drawable/shape_gray100_fill_gray400_stroke_99_rect.xml
  app/src/main/res/drawable/shape_white_fill_gray000_stroke_99_rect.xml
  app/src/main/res/drawable/shape_white_fill_gray100_stroke_100_circle.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_onboarding_choice_routine.xml
  app/src/main/res/layout/fragment_onboarding_choice_theme.xml
  app/src/main/res/layout/item_onboarding_choice_routine.xml
  app/src/main/res/layout/item_onboarding_choice_theme.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request, Feat, 민정🦊

#35 #30 [feat] 설정 뷰 + 공통 바텀시트
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopetit/softie/ui/setting/SampleActivity.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingActivity.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingInitFragment.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingUserExitFragment.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingUserSecurityFragment.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingViewModel.kt
  app/src/main/java/com/sopetit/softie/util/OriginalBottomSheet.kt
  app/src/main/java/com/sopetit/softie/util/binding/BindingBottomSheet.kt
  app/src/main/res/drawable/ic_bear_brown_crying.png
  app/src/main/res/drawable/ic_bear_face_1.xml
  app/src/main/res/drawable/ic_bear_face_crying.xml
  app/src/main/res/drawable/ic_bear_gray_crying.png
  app/src/main/res/drawable/ic_bear_panda_crying.png
  app/src/main/res/drawable/ic_bear_red_crying.png
  app/src/main/res/drawable/ic_document.xml
  app/src/main/res/drawable/ic_feedback.xml
  app/src/main/res/drawable/ic_guide.xml
  app/src/main/res/drawable/ic_right_btn.xml
  app/src/main/res/drawable/ic_speech_bottom.xml
  app/src/main/res/drawable/ic_user_security.xml
  app/src/main/res/drawable/shape_gray000_fill_top20_rect.xml
  app/src/main/res/drawable/shape_red_fill_12_rect.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/fragment_bottomsheet.xml
  app/src/main/res/layout/fragment_onboarding_choice_routine.xml
  app/src/main/res/layout/fragment_onboarding_choice_theme.xml
  app/src/main/res/layout/fragment_setting_init.xml
  app/src/main/res/layout/fragment_setting_user_exit.xml
  app/src/main/res/layout/fragment_setting_user_security.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Pull Request, Feat, 민정🦊

#34 #19 [ui] 데일리 루틴 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineActivity.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineedit/DailyRoutineEditActivity.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineedit/DailyRoutineEditViewModel.kt
  app/src/main/res/drawable/ic_daily.xml
  app/src/main/res/drawable/ic_daily_fin.xml
  app/src/main/res/drawable/ic_daily_plus.xml
  app/src/main/res/drawable/ic_radio_click.xml
  app/src/main/res/drawable/ic_radio_empty.xml
  app/src/main/res/drawable/selector_daily_edit.xml
  app/src/main/res/drawable/shape_gray100_fill_10_rect.xml
  app/src/main/res/drawable/shape_gray200_line_20_rect.xml
  app/src/main/res/drawable/shape_main1_fill_10_rect.xml
  app/src/main/res/drawable/shape_white_fill_gray100_stroke_20_rect.xml
  app/src/main/res/layout/activity_daily_routine_edit.xml
  app/src/main/res/layout/activity_sample.xml
  app/src/main/res/layout/fragment_daily_routine.xml
  app/src/main/res/values/strings.xml
Labels: UI, 민회🐹

#37 #33 [ui] 바텀 네비게이션 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineActivity.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineedit/DailyRoutineEditActivity.kt
  app/src/main/java/com/sopetit/softie/ui/main/MainActivity.kt
  app/src/main/java/com/sopetit/softie/ui/main/happy/HappyActivity.kt
  app/src/main/java/com/sopetit/softie/ui/main/happy/HappyEmptyFragment.kt
  app/src/main/java/com/sopetit/softie/ui/main/happy/HappyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/main/home/HomeFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceFragment.kt
  app/src/main/res/drawable/ic_happiness_routine_default.xml
  app/src/main/res/drawable/ic_happiness_routine_variant.xml
  app/src/main/res/drawable/ic_home_default.xml
  app/src/main/res/drawable/ic_home_variant.xml
  app/src/main/res/drawable/ic_progress_default.xml
  app/src/main/res/drawable/ic_progress_variant.xml
  app/src/main/res/drawable/selector_bottom_navigation_happiness_routine.xml
  app/src/main/res/drawable/selector_bottom_navigation_home.xml
  app/src/main/res/drawable/selector_bottom_navigation_progress.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_daily_routine.xml
  app/src/main/res/layout/fragment_happy_routine.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/menu/bottom_navigation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: UI, Pull Request, 강희🐬

#28 #25 [fix] 온보딩 테마 선택 뷰 이슈 해결
  app/src/main/java/com/sopetit/softie/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/themechoice/ChoiceThemeAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/themechoice/ChoiceThemeFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/themechoice/ChoiceThemeViewModel.kt
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_onboarding_choice_routine.xml
  app/src/main/res/layout/fragment_onboarding_choice_theme.xml
Labels: Pull Request, 민정🦊, fix

#29 #27 [feat] 스플래쉬 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopetit/softie/ui/main/LoginActivity.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/splash/SplashActivity.kt
  app/src/main/res/drawable/ic_login_kakao.xml
  app/src/main/res/drawable/ic_logo_main1.xml
  app/src/main/res/drawable/ic_speech_dark.xml
  app/src/main/res/drawable/ic_splash1.png
  app/src/main/res/drawable/ic_splash2.png
  app/src/main/res/drawable/ic_splash3.png
  app/src/main/res/drawable/ic_splash4.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request, Feat, 민정🦊

#41 #40 [ui] 온보딩 테마&루틴 선택 뷰 수정
  app/src/main/res/drawable/shape_background_gradation_bot_fill_0_rect.xml
  app/src/main/res/drawable/shape_background_gradation_top_fill_0_rect.xml
  app/src/main/res/layout/fragment_onboarding_choice_routine.xml
  app/src/main/res/layout/fragment_onboarding_choice_theme.xml
Labels: UI, Pull Request, 민정🦊, fix

#45 #42 [feat] 데일리 루틴
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopetit/softie/domain/entity/DailyRoutine.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineedit/DailyRoutineEditActivity.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineedit/DailyRoutineEditViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingInitFragment.kt
  app/src/main/java/com/sopetit/softie/util/Context.kt
  app/src/main/java/com/sopetit/softie/util/CustomSnackbar.kt
  app/src/main/java/com/sopetit/softie/util/OriginalBottomSheet.kt
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/shape_gray300_fill_8_rect.xml
  app/src/main/res/layout/activity_daily_routine_edit.xml
  app/src/main/res/layout/fragment_bottomsheet.xml
  app/src/main/res/layout/fragment_daily_routine.xml
  app/src/main/res/layout/snackbar_custom.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request, Feat, 민정🦊

#18 #8 [ui] Daily Routine - 추가하기
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopetit/softie/domain/entity/DailyCard.kt
  app/src/main/java/com/sopetit/softie/domain/entity/DailyRoutineAdd.kt
  app/src/main/java/com/sopetit/softie/domain/entity/Theme.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddActivity.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddCardPagerAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddThemeAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddViewModel.kt
  app/src/main/res/drawable/ic_daily_add.xml
  app/src/main/res/drawable/ic_daily_back.xml
  app/src/main/res/drawable/ic_daily_routine_card.xml
  app/src/main/res/drawable/selector_daily_indicator.xml
  app/src/main/res/drawable/shape_black_fill_100_circle.xml
  app/src/main/res/drawable/shape_black_fill_20_rect.xml
  app/src/main/res/drawable/shape_gray_fill_100_circle.xml
  app/src/main/res/drawable/shape_gray_fill_20_rect.xml
  app/src/main/res/drawable/shape_white_fill_100_circle_click.xml
  app/src/main/res/layout/activity_daily_routine_add.xml
  app/src/main/res/layout/item_daily_routine_add_card.xml
  app/src/main/res/layout/item_daily_routine_add_theme.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: UI, 민회🐹

#47 #46 [ui] 루틴 완료 시 보이는 화면
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopetit/softie/domain/entity/Bear.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineCompleteActivity.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyRoutineCompleteActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/addlist/HappyAddListChipContentAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/addlist/HappyAddListContentAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/addlist/HappyAddListViewModel.kt
  app/src/main/java/com/sopetit/softie/util/Context.kt
  app/src/main/java/com/sopetit/softie/util/RoutineCompleteActivity.kt
  app/src/main/java/com/sopetit/softie/util/binding/BindingActivity.kt
  app/src/main/res/drawable/ic_bear_handsup_brown.png
  app/src/main/res/drawable/ic_bear_handsup_gray.png
  app/src/main/res/drawable/ic_bear_handsup_panda.png
  app/src/main/res/drawable/ic_bear_handsup_red.png
  app/src/main/res/drawable/ic_bear_happy_complete_brown.png
  app/src/main/res/drawable/ic_bear_happy_complete_gray.png
  app/src/main/res/drawable/ic_bear_happy_complete_panda.png
  app/src/main/res/drawable/ic_bear_happy_complete_red.png
  app/src/main/res/drawable/shape_gray100_fill_8_rect.xml
  app/src/main/res/layout/activity_routine_complete.xml
  app/src/main/res/raw/daily_complete_som.json
  app/src/main/res/raw/happy_complete_som.json
  app/src/main/res/values/strings.xml
Labels: UI, Pull Request, 강희🐬

#53 [ui] 행복루틴 진행 뷰
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopetit/softie/domain/entity/HappyProgress.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/adddetail/HappyDetailActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/progress/HappyProgressFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/progress/HappyProgressViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/main/MainActivity.kt
  app/src/main/res/drawable/ic_speech_happy.xml
  app/src/main/res/layout/activity_happy_add_detail.xml
  app/src/main/res/layout/fragment_happy_progress.xml
  app/src/main/res/values/strings.xml
Labels: UI, 호연🐻‍❄️

#55 #49 [UI] 상태바 색상 수정 및 뷰 연결
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineCompleteActivity.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyRoutineCompleteActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/adddetail/HappyDetailActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/addlist/HappyAddListActivity.kt
  app/src/main/java/com/sopetit/softie/ui/main/LoginActivity.kt
  app/src/main/java/com/sopetit/softie/ui/main/MainActivity.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearnaming/BearNamingViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/splash/SplashActivity.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingActivity.kt
  app/src/main/res/layout/activity_daily_routine_add.xml
  app/src/main/res/layout/activity_routine_complete.xml
  app/src/main/res/layout/activity_sample.xml
  app/src/main/res/layout/fragment_happy_progress.xml
  app/src/main/res/layout/fragment_happy_routine.xml
  app/src/main/res/layout/fragment_onboarding_bear_naming.xml
  app/src/main/res/layout/fragment_onboarding_bear_selection.xml
  app/src/main/res/values/themes.xml
Labels: UI, Pull Request, 강희🐬

#56 #50 [ui] 바텀시트, 스낵바, 스플래시 로고 수정
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineedit/DailyRoutineEditActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/adddetail/HappyDetailActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/adddetail/HappyDetailCardPagerAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/adddetail/HappyDetailCardViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/progress/HappyProgressFragment.kt
  app/src/main/java/com/sopetit/softie/ui/main/MainActivity.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/splash/SplashActivity.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingInitFragment.kt
  app/src/main/res/drawable/ic_logo_main2.xml
  app/src/main/res/drawable/ic_splash1.png
  app/src/main/res/drawable/ic_splash2.png
  app/src/main/res/drawable/ic_splash3.png
  app/src/main/res/drawable/ic_splash4.png
  app/src/main/res/drawable/ic_splash_backround1.png
  app/src/main/res/drawable/ic_splash_backround2.png
  app/src/main/res/drawable/ic_splash_backround3.png
  app/src/main/res/drawable/ic_splash_backround4.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_happy_progress.xml
  app/src/main/res/layout/item_happy_add_list.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Pull Request, 강희🐬, fix

#60 #57 [ui] 데일리루틴 추가하기 바텀시트
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddActivity.kt
  app/src/main/java/com/sopetit/softie/ui/main/MainActivity.kt
  app/src/main/res/values/strings.xml
Labels: UI, Pull Request, 민회🐹

#70 #65 [feat] home 솜 api 작업
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopetit/softie/data/entity/request/SampleRequest.kt
  app/src/main/java/com/sopetit/softie/data/entity/response/CottonCountResponse.kt
  app/src/main/java/com/sopetit/softie/data/repositoryImpl/MemberRepositoryImpl.kt
  app/src/main/java/com/sopetit/softie/data/service/MemberService.kt
  app/src/main/java/com/sopetit/softie/data/source/MemberDataSource.kt
  app/src/main/java/com/sopetit/softie/domain/entity/CottonCount.kt
  app/src/main/java/com/sopetit/softie/domain/entity/Sample.kt
  app/src/main/java/com/sopetit/softie/domain/repository/MemberRepository.kt
  app/src/main/java/com/sopetit/softie/domain/repository/SampleRepository.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/PatchCottonUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/PostLoginUseCase.kt
  app/src/main/java/com/sopetit/softie/ui/main/home/HomeFragment.kt
  app/src/main/java/com/sopetit/softie/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/sopetit/softie/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/img_homeback_all.xml
  app/src/main/res/layout/fragment_home.xml
Labels: Pull Request, Feat, 강희🐬

#71 #38 [feat] 온보딩 테마&루틴 선택 서버통신
  app/build.gradle.kts
  app/src/main/java/com/sopetit/softie/data/entity/response/DailyRoutineListResponse.kt
  app/src/main/java/com/sopetit/softie/data/entity/response/DollResponse.kt
  app/src/main/java/com/sopetit/softie/data/entity/response/ThemeListResponse.kt
  app/src/main/java/com/sopetit/softie/data/repositoryImpl/DailyRoutineRepositoryImpl.kt
  app/src/main/java/com/sopetit/softie/data/repositoryImpl/DollRepositoryImpl.kt
  app/src/main/java/com/sopetit/softie/data/service/DailyRoutineService.kt
  app/src/main/java/com/sopetit/softie/data/service/DollService.kt
  app/src/main/java/com/sopetit/softie/data/source/DailyRoutineDataSource.kt
  app/src/main/java/com/sopetit/softie/data/source/DollDataSource.kt
  app/src/main/java/com/sopetit/softie/di/RepositoryModule.kt
  app/src/main/java/com/sopetit/softie/di/RetrofitServiceModule.kt
  app/src/main/java/com/sopetit/softie/domain/repository/DailyRoutineRepository.kt
  app/src/main/java/com/sopetit/softie/domain/repository/DollRepository.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/dailyroutine/GetRoutineListUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/dailyroutine/GetThemeListUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/doll/GetDollUseCase.kt
  app/src/main/java/com/sopetit/softie/ui/LoadingIndicator.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearselection/BearSelectionFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearselection/BearSelectionViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/themechoice/ChoiceThemeAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/themechoice/ChoiceThemeFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/themechoice/ChoiceThemeViewModel.kt
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_onboarding_choice_theme.xml
  app/src/main/res/layout/loading_indicator.xml
Labels: Pull Request, Feat, 민정🦊

#67 #64 [feat] 행복 루틴 추가하기(목록) 뷰 API 연결
  app/src/main/java/com/sopetit/softie/data/entity/response/HappyChipResponse.kt
  app/src/main/java/com/sopetit/softie/data/entity/response/HappyContentResponse.kt
  app/src/main/java/com/sopetit/softie/data/repositoryImpl/HappinessRoutineRepositoryImpl.kt
  app/src/main/java/com/sopetit/softie/data/service/HappinessRoutineService.kt
  app/src/main/java/com/sopetit/softie/data/source/HappinessRoutineDataSource.kt
  app/src/main/java/com/sopetit/softie/di/RepositoryModule.kt
  app/src/main/java/com/sopetit/softie/di/RetrofitServiceModule.kt
  app/src/main/java/com/sopetit/softie/domain/entity/HappyContent.kt
  app/src/main/java/com/sopetit/softie/domain/repository/HappinessRoutineRepository.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/GetHappyChipUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/GetHappyContentUseCase.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/addlist/HappyAddListActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/addlist/HappyAddListContentAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/addlist/HappyAddListViewModel.kt
Labels: UI, 호연🐻‍❄️

#75 #68 [feat] 행복 루틴 추가하기(상세) 뷰 API 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopetit/softie/data/entity/response/HappyCardResponse.kt
  app/src/main/java/com/sopetit/softie/data/repositoryImpl/HappinessRoutineRepositoryImpl.kt
  app/src/main/java/com/sopetit/softie/data/service/HappinessRoutineService.kt
  app/src/main/java/com/sopetit/softie/data/source/HappinessRoutineDataSource.kt
  app/src/main/java/com/sopetit/softie/di/RepositoryModule.kt
  app/src/main/java/com/sopetit/softie/di/RetrofitServiceModule.kt
  app/src/main/java/com/sopetit/softie/domain/entity/HappyCard.kt
  app/src/main/java/com/sopetit/softie/domain/repository/HappinessRoutineRepository.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/GetHappyCardUseCase.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/adddetail/HappyDetailCardViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/detail/HappyDetailActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/detail/HappyDetailCardPagerAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/detail/HappyDetailCardViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListChipContentAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListContentAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListViewModel.kt
  app/src/main/res/layout/activity_happy_add_detail.xml
  app/src/main/res/layout/fragment_bottomsheet.xml
  app/src/main/res/layout/item_happy_add_detail_card.xml
Labels: UI, 호연🐻‍❄️

#59 #52 [fix] 행복루틴 엠티뷰 서버 연결
  app/src/main/java/com/sopetit/softie/di/RepositoryModule.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyRoutineViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/main/home/HomeFragment.kt
  app/src/main/java/com/sopetit/softie/ui/main/home/HomeViewModel.kt
  app/src/main/res/drawable/ic_bear_face_2.xml
  app/src/main/res/drawable/ic_bear_face_3.xml
  app/src/main/res/drawable/ic_bear_face_4.xml
  app/src/main/res/layout/fragment_happy_routine.xml
Labels: UI, 호연🐻‍❄️

#82 #72 [feat] 카카오 로그인 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopetit/softie/SoftieApplication.kt
  app/src/main/java/com/sopetit/softie/data/entity/request/LoginRequest.kt
  app/src/main/java/com/sopetit/softie/data/entity/response/LoginResponse.kt
  app/src/main/java/com/sopetit/softie/data/repositoryImpl/AuthRepositoryImpl.kt
  app/src/main/java/com/sopetit/softie/data/service/AuthService.kt
  app/src/main/java/com/sopetit/softie/data/service/KakaoLoginService.kt
  app/src/main/java/com/sopetit/softie/data/source/AuthDataSource.kt
  app/src/main/java/com/sopetit/softie/data/source/LocalDataSource.kt
  app/src/main/java/com/sopetit/softie/di/RepositoryModule.kt
  app/src/main/java/com/sopetit/softie/di/RetrofitModule.kt
  app/src/main/java/com/sopetit/softie/di/RetrofitServiceModule.kt
  app/src/main/java/com/sopetit/softie/di/SharedPrefModule.kt
  app/src/main/java/com/sopetit/softie/domain/entity/Token.kt
  app/src/main/java/com/sopetit/softie/domain/repository/AuthRepository.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/GetSignedUpUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/InitSIgnUpStateUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/InitTokenUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/PostLoginUseCase.kt
  app/src/main/java/com/sopetit/softie/ui/login/LoginActivity.kt
  app/src/main/java/com/sopetit/softie/ui/login/LoginViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/main/LoginActivity.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/splash/SplashActivity.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/splash/SplashViewModel.kt
  app/src/main/java/com/sopetit/softie/util/ActivityExt.kt
  app/src/main/java/com/sopetit/softie/util/KakaoLoginCallback.kt
  app/src/main/java/com/sopetit/softie/util/OnSingleClickListener.kt
  app/src/main/res/drawable/ic_kakao_login.png
  app/src/main/res/drawable/ic_login_kakao.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/raw/brown_eating_daily.json
  app/src/main/res/values/strings.xml
  build.gradle.kts
  settings.gradle.kts
Labels: Pull Request, 강희🐬

#77 #73 [feat] 프로필 생성 서버 통신
  app/build.gradle.kts
  app/src/main/java/com/sopetit/softie/data/entity/request/PostMemberRequest.kt
  app/src/main/java/com/sopetit/softie/data/repositoryImpl/MemberRepositoryImpl.kt
  app/src/main/java/com/sopetit/softie/data/service/MemberService.kt
  app/src/main/java/com/sopetit/softie/data/source/MemberDataSource.kt
  app/src/main/java/com/sopetit/softie/domain/repository/MemberRepository.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/member/PostMemberUseCase.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyRoutineViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/main/home/HomeFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearnaming/BearNamingFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearselection/BearSelectionFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearselection/BearSelectionViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceViewModel.kt
  app/src/main/res/layout/fragment_onboarding_bear_selection.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request, Feat, 민정🦊

#78 #74 [feat] 회원 탈퇴 서버통신
  app/src/main/java/com/sopetit/softie/data/repositoryImpl/AuthRepositoryImpl.kt
  app/src/main/java/com/sopetit/softie/data/service/AuthService.kt
  app/src/main/java/com/sopetit/softie/data/source/AuthDataSource.kt
  app/src/main/java/com/sopetit/softie/di/RepositoryModule.kt
  app/src/main/java/com/sopetit/softie/di/RetrofitServiceModule.kt
  app/src/main/java/com/sopetit/softie/domain/repository/AuthRepository.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/auth/DeleteAuthUseCase.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingActivity.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingUserExitFragment.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingViewModel.kt
Labels: Pull Request, Feat, 민정🦊

#83 #76 [feat] 행복루틴 추가 API 연결 및 뷰페이저 subRoutineId 옵저빙
  app/src/main/java/com/sopetit/softie/data/entity/request/PostMemberHappyRoutineRequest.kt
  app/src/main/java/com/sopetit/softie/data/entity/response/MemberHappyRoutinePostResponse.kt
  app/src/main/java/com/sopetit/softie/data/repositoryImpl/MemberHappinessRoutineRepositoryImpl.kt
  app/src/main/java/com/sopetit/softie/data/service/MemberHappinessRoutineService.kt
  app/src/main/java/com/sopetit/softie/data/source/MemberHappinessRoutineDataSource.kt
  app/src/main/java/com/sopetit/softie/di/RepositoryModule.kt
  app/src/main/java/com/sopetit/softie/di/RetrofitServiceModule.kt
  app/src/main/java/com/sopetit/softie/domain/repository/MemberHappinessRoutineRepository.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/PostMemberHappyRoutineUseCase.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/detail/HappyDetailActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/detail/HappyDetailCardPagerAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/detail/HappyDetailCardViewModel.kt
Labels: UI, 호연🐻‍❄️

#80 #79 [fix] 자잘한 이슈 해결
  app/src/main/java/com/sopetit/softie/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/com/sopetit/softie/util/Context.kt
  app/src/main/res/layout/fragment_onboarding_choice_routine.xml
  app/src/main/res/layout/fragment_onboarding_choice_theme.xml
  app/src/main/res/layout/item_onboarding_choice_theme.xml
Labels: Pull Request, 민정🦊, fix

#69 #66 [feat] 유저별 데일리루틴 리스트 조회 api 연결
  app/src/main/java/com/sopetit/softie/data/entity/request/AddDailyRoutineRequest.kt
  app/src/main/java/com/sopetit/softie/data/entity/response/AchieveDailyResponse.kt
  app/src/main/java/com/sopetit/softie/data/entity/response/AddDailyRoutineResponse.kt
  app/src/main/java/com/sopetit/softie/data/entity/response/DailyCardResponse.kt
  app/src/main/java/com/sopetit/softie/data/entity/response/DailyRoutineResponse.kt
  app/src/main/java/com/sopetit/softie/data/repositoryImpl/DailyRoutineRepositoryImpl.kt
  app/src/main/java/com/sopetit/softie/data/service/DailyRoutineService.kt
  app/src/main/java/com/sopetit/softie/data/source/DailyRoutineDataSource.kt
  app/src/main/java/com/sopetit/softie/domain/entity/AddRoutine.kt
  app/src/main/java/com/sopetit/softie/domain/entity/DailyAchieve.kt
  app/src/main/java/com/sopetit/softie/domain/entity/UserDailyRoutine.kt
  app/src/main/java/com/sopetit/softie/domain/repository/DailyRoutineRepository.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/DeleteDailyRoutineUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/GetDailyRoutineUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/PatchAchieveDailyUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/PostAddDailyRoutineUseCase.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddActivity.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddViewModel.kt
  app/src/main/res/layout/fragment_daily_routine.xml
Labels: Feat, 민회🐹

#88 #85 [hotfix] 홈 뷰 로티 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopetit/softie/data/repositoryImpl/AuthRepositoryImpl.kt
  app/src/main/java/com/sopetit/softie/data/source/LocalDataSource.kt
  app/src/main/java/com/sopetit/softie/domain/entity/Bear.kt
  app/src/main/java/com/sopetit/softie/domain/repository/AuthRepository.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/GetBearTypeUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/member/SetBearTypeUseCase.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineCompleteActivity.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/complete/DailyRoutineCompleteActivity.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/complete/DailyRoutineCompleteViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyRoutineCompleteActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyRoutineViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/complete/HappyRoutineCompleteActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/complete/HappyRoutineCompleteViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/progress/HappyProgressFragment.kt
  app/src/main/java/com/sopetit/softie/ui/main/home/HomeFragment.kt
  app/src/main/java/com/sopetit/softie/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearselection/BearSelectionFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearselection/BearSelectionViewModel.kt
  app/src/main/res/layout/activity_routine_complete.xml
  app/src/main/res/layout/fragment_happy_routine.xml
  app/src/main/res/layout/fragment_home.xml
Labels: hotfix🚨, 강희🐬

#89 #81 [feat] 유저별 행복루틴 조회, 행복루틴 삭제하기 API 연결
  app/src/main/java/com/sopetit/softie/data/entity/response/HappyProgressResponse.kt
  app/src/main/java/com/sopetit/softie/data/repositoryImpl/MemberHappinessRoutineRepositoryImpl.kt
  app/src/main/java/com/sopetit/softie/data/service/MemberHappinessRoutineService.kt
  app/src/main/java/com/sopetit/softie/data/source/MemberHappinessRoutineDataSource.kt
  app/src/main/java/com/sopetit/softie/domain/entity/HappyProgress.kt
  app/src/main/java/com/sopetit/softie/domain/repository/MemberHappinessRoutineRepository.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/DeleteMemberHappyRoutineUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/GetHappyProgressUseCase.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/delete/HappyDeleteFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/progress/HappyProgressFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/progress/HappyProgressViewModel.kt
  app/src/main/res/drawable/ic_happycard.xml
  app/src/main/res/layout/fragment_happy_delete.xml
  app/src/main/res/layout/fragment_happy_progress.xml
  app/src/main/res/layout/item_happy_add_detail_card.xml
Labels: UI, 호연🐻‍❄️

#87 #84 [feat] 로그아웃 구현
  app/src/main/java/com/sopetit/softie/data/repositoryImpl/AuthRepositoryImpl.kt
  app/src/main/java/com/sopetit/softie/data/service/AuthService.kt
  app/src/main/java/com/sopetit/softie/data/source/AuthDataSource.kt
  app/src/main/java/com/sopetit/softie/domain/repository/AuthRepository.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/auth/LogOutUseCase.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingInitFragment.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingUserExitFragment.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingViewModel.kt
Labels: Pull Request, Feat, 민정🦊

#94 #91 [feat] 행복루틴 달성 API 연결
  app/src/main/java/com/sopetit/softie/data/repositoryImpl/MemberHappinessRoutineRepositoryImpl.kt
  app/src/main/java/com/sopetit/softie/data/service/MemberHappinessRoutineService.kt
  app/src/main/java/com/sopetit/softie/data/source/MemberHappinessRoutineDataSource.kt
  app/src/main/java/com/sopetit/softie/domain/repository/MemberHappinessRoutineRepository.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/PatchMemberHappinessAchieveUseCase.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/progress/HappyProgressFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/progress/HappyProgressViewModel.kt
Labels: UI, 호연🐻‍❄️

#100 #97 [ui] 테마별 행복루틴 리스트 칩 QA 반영
  app/src/main/java/com/sopetit/softie/domain/usecase/happyroutine/GetHappyCardUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/happyroutine/GetHappyChipUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/happyroutine/GetHappyContentUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/happyroutine/PostMemberHappyRoutineUseCase.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/detail/HappyDetailCardViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListChipContentAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListViewModel.kt
Labels: UI, 호연🐻‍❄️

#96 #95 [feat] 달성 완료 후 바텀시트에 해당 아이콘 띄우기
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/util/OriginalBottomSheet.kt
Labels: Feat, 민회🐹

#105 #62 [feat] 데일리 루틴 카드 api 연결 및 루틴 추가
  app/src/main/java/com/sopetit/softie/data/entity/response/DailyCardResponse.kt
  app/src/main/java/com/sopetit/softie/data/entity/response/RoutineItemEntity.kt
  app/src/main/java/com/sopetit/softie/data/repositoryImpl/DailyRoutineRepositoryImpl.kt
  app/src/main/java/com/sopetit/softie/data/service/DailyRoutineService.kt
  app/src/main/java/com/sopetit/softie/data/source/DailyRoutineDataSource.kt
  app/src/main/java/com/sopetit/softie/domain/entity/DailyCard.kt
  app/src/main/java/com/sopetit/softie/domain/repository/DailyRoutineRepository.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/GetRoutineDailyThemeListUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/PostAddDailyRoutineUseCase.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddActivity.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddCardPagerAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddThemeAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddViewModel.kt
  app/src/main/res/drawable/img_homeback_all.png
  app/src/main/res/drawable/img_homeback_all.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_daily_routine_add_card.xml
Labels: Pull Request, Feat, 강희🐬

#98 #90 [fix] 카카오 로그인 버튼 수정
  app/src/main/res/drawable/ic_girl1.png
  app/src/main/res/drawable/ic_girl2.png
  app/src/main/res/drawable/ic_girl5.png
  app/src/main/res/drawable/ic_girl6.png
  app/src/main/res/drawable/ic_kakao_login.png
  app/src/main/res/drawable/ic_kakao_login.xml
  app/src/main/res/layout/fragment_story_telling_intro.xml
  app/src/main/res/layout/fragment_story_telling_main.xml
Labels: 민회🐹, fix

#102 #99 [fix] 데일리 루틴 1차 qa
  app/src/main/res/layout/fragment_daily_routine.xml
Labels: 민회🐹, fix

#106 #103 [fix] 루틴 달성 완료 뷰 qa
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/complete/DailyRoutineCompleteActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/complete/HappyRoutineCompleteActivity.kt
  app/src/main/res/drawable/ic_daily_complete_brown.xml
  app/src/main/res/drawable/ic_daily_complete_gray.xml
  app/src/main/res/drawable/ic_daily_complete_panda.xml
  app/src/main/res/drawable/ic_daily_complete_red.xml
  app/src/main/res/drawable/ic_happy_complete_brown.xml
  app/src/main/res/drawable/ic_happy_complete_gray.xml
  app/src/main/res/drawable/ic_happy_complete_panda.xml
  app/src/main/res/drawable/ic_happy_complete_red.xml
  app/src/main/res/layout/activity_routine_complete.xml
Labels: 민회🐹, fix

#107 #104 [fix] 바텀시트 이슈 해결
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddActivity.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddCardPagerAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddThemeAdapter.kt
Labels: Pull Request, 민정🦊, fix

#112 #110 [fix] 버튼 터치영역 수정 및 웹사이트 연결
  app/src/main/java/com/sopetit/softie/ui/main/home/HomeFragment.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingInitFragment.kt
  app/src/main/res/layout/activity_daily_routine_add.xml
  app/src/main/res/layout/activity_happy_add_detail.xml
  app/src/main/res/layout/activity_happy_add_list.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/fragment_daily_routine.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: 민회🐹, fix

#116 #113 [fix] 데일리 루틴 추가하기 qa
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddActivity.kt
  app/src/main/res/layout/item_daily_routine_add_card.xml
Labels: 민회🐹, fix

#119 #118 [refact] 클릭리스너 확장함수로 고치기
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddActivity.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddThemeAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/delete/HappyDeleteFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/detail/HappyDetailActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/detail/HappyDetailCardPagerAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListChipContentAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListContentAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/progress/HappyProgressFragment.kt
  app/src/main/java/com/sopetit/softie/ui/login/LoginActivity.kt
  app/src/main/java/com/sopetit/softie/ui/main/home/HomeFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearnaming/BearNamingFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearselection/BearSelectionFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/themechoice/ChoiceThemeAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/themechoice/ChoiceThemeFragment.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingActivity.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingInitFragment.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingUserExitFragment.kt
  app/src/main/java/com/sopetit/softie/ui/storytelling/StoryTellingConclusionFragment.kt
  app/src/main/java/com/sopetit/softie/ui/storytelling/StoryTellingIntroFragment.kt
  app/src/main/java/com/sopetit/softie/ui/storytelling/StoryTellingMainFragment.kt
  app/src/main/java/com/sopetit/softie/util/Context.kt
  app/src/main/java/com/sopetit/softie/util/OriginalBottomSheet.kt
Labels: Refactor, 민회🐹

#114 #92 [hotfix] 닉네임 10글자 제한
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearnaming/BearNamingFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearnaming/BearNamingViewModel.kt
  app/src/main/res/layout/fragment_onboarding_bear_naming.xml
  app/src/main/res/values/strings.xml
Labels: hotfix🚨, Pull Request, 강희🐬

#115 #111 [hotfix] 데일리 루틴 추가 시 아무것도 누르지 않고 추가했을 때 앱 터짐 이슈 해결
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddActivity.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddCardPagerAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddThemeAdapter.kt
  app/src/main/res/values/strings.xml
Labels: hotfix🚨, Pull Request, 강희🐬

#123 #121 [fix] 로티 끝나기 전까지는 로티 재생 안되게 막기
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddActivity.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddCardPagerAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddThemeAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/delete/HappyDeleteFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/detail/HappyDetailActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/detail/HappyDetailCardPagerAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListChipContentAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListContentAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/progress/HappyProgressFragment.kt
  app/src/main/java/com/sopetit/softie/ui/login/LoginActivity.kt
  app/src/main/java/com/sopetit/softie/ui/main/home/HomeFragment.kt
  app/src/main/java/com/sopetit/softie/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearnaming/BearNamingFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearnaming/BearNamingViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearselection/BearSelectionFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/themechoice/ChoiceThemeAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/themechoice/ChoiceThemeFragment.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingActivity.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingInitFragment.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingUserExitFragment.kt
  app/src/main/java/com/sopetit/softie/util/OriginalBottomSheet.kt
  app/src/main/res/layout/activity_daily_routine_add.xml
  app/src/main/res/layout/activity_happy_add_detail.xml
  app/src/main/res/layout/activity_happy_add_list.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/fragment_daily_routine.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_onboarding_bear_naming.xml
  app/src/main/res/layout/item_daily_routine_add_card.xml
  app/src/main/res/values/strings.xml
Labels: 강희🐬, fix

#124 #122 [fix] 데일리 루틴 삭제 후 초기화 시키기
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineViewModel.kt
  app/src/main/res/layout/fragment_daily_routine.xml
Labels: 민회🐹, fix

#129 #125 [fix] 전체 1차 qa 자잘자잘 이슈
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/delete/HappyDeleteFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/detail/HappyDetailCardPagerAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/themechoice/ChoiceThemeAdapter.kt
  app/src/main/java/com/sopetit/softie/util/OriginalBottomSheet.kt
  app/src/main/res/values/colors.xml
Labels: 민회🐹, fix

#127 #108 [fix] 이슈 해결
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceFragment.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingUserExitFragment.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingViewModel.kt
  app/src/main/res/layout/fragment_setting_init.xml
Labels: Pull Request, 민정🦊, fix

#128 #101 [fix] 행복루틴 QA 이슈 해결
  app/src/main/java/com/sopetit/softie/domain/usecase/happyroutine/GetHappyProgressUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/happyroutine/PatchMemberHappinessAchieveUseCase.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyMyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyMyRoutineViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyRoutineViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/delete/HappyDeleteFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/detail/HappyDetailActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListChipContentAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListContentAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/main/MainActivity.kt
  app/src/main/java/com/sopetit/softie/util/Context.kt
  app/src/main/res/drawable/ic_bear_base.xml
  app/src/main/res/drawable/ic_happy_bling_blue.xml
  app/src/main/res/drawable/ic_happy_bling_green.xml
  app/src/main/res/drawable/ic_happy_bling_orange.xml
  app/src/main/res/drawable/ic_happy_bling_purple.xml
  app/src/main/res/drawable/ic_happy_bling_red.xml
  app/src/main/res/drawable/ic_happy_blue.xml
  app/src/main/res/drawable/ic_happy_green.xml
  app/src/main/res/drawable/ic_happy_orange.xml
  app/src/main/res/drawable/ic_happy_purple.xml
  app/src/main/res/drawable/ic_happy_red.xml
  app/src/main/res/drawable/ic_happycard.xml
  app/src/main/res/drawable/ic_loading_bear.xml
  app/src/main/res/drawable/ic_theme_1.xml
  app/src/main/res/layout/activity_happy_add_detail.xml
  app/src/main/res/layout/fragment_happy_delete.xml
  app/src/main/res/layout/fragment_happy_my_routine.xml
  app/src/main/res/layout/fragment_happy_progress.xml
  app/src/main/res/layout/fragment_happy_routine.xml
  app/src/main/res/layout/item_happy_add_detail_card.xml
  app/src/main/res/layout/item_happy_add_list.xml
  app/src/main/res/layout/item_onboarding_choice_theme.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 호연🐻‍❄️, fix

#140 #133 [fix] 닉네임 숫자 방지 및 10글자 경고문
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearnaming/BearNamingFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearnaming/BearNamingViewModel.kt
  app/src/main/res/values/strings.xml
Labels: Pull Request, 강희🐬, fix
