Repository Team-Sopetit/Sopetit-Android, pull requests merged in 2024-02, with the labels that each got.

#146 #135 [fix] 릴리즈 전 QA 이슈 수정
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearnaming/BearNamingFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearnaming/BearNamingViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingUserExitFragment.kt
  app/src/main/res/color/selector_onboarding_routine_text.xml
  app/src/main/res/drawable/ic_bear_brown_crying.png
  app/src/main/res/drawable/ic_bear_gray_crying.png
  app/src/main/res/drawable/ic_bear_panda_crying.png
  app/src/main/res/drawable/ic_bear_red_crying.png
  app/src/main/res/drawable/ic_bear_white_crying.png
  app/src/main/res/drawable/selector_onboarding_routine_background.xml
  app/src/main/res/layout/fragment_setting_user_exit.xml
  app/src/main/res/layout/item_onboarding_choice_routine.xml
Labels: Pull Request, 민정🦊, fix

#148 #147 [mod] 설정뷰 수정사항 반영
  app/src/main/java/com/sopetit/softie/ui/setting/SettingInitFragment.kt
  app/src/main/res/layout/fragment_setting_init.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request, Feat, 민정🦊

#149 #142 [feat] 버전에 따른 다이얼로그
  app/build.gradle.kts
  app/src/main/java/com/sopetit/softie/data/entity/response/VersionResponse.kt
  app/src/main/java/com/sopetit/softie/data/repositoryImpl/VersionRepositoryImpl.kt
  app/src/main/java/com/sopetit/softie/data/service/VersionService.kt
  app/src/main/java/com/sopetit/softie/data/source/VersionDataSource.kt
  app/src/main/java/com/sopetit/softie/di/RepositoryModule.kt
  app/src/main/java/com/sopetit/softie/di/RetrofitServiceModule.kt
  app/src/main/java/com/sopetit/softie/di/VersionModule.kt
  app/src/main/java/com/sopetit/softie/domain/entity/UpdateType.kt
  app/src/main/java/com/sopetit/softie/domain/entity/UpdateVersion.kt
  app/src/main/java/com/sopetit/softie/domain/repository/VersionRepository.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/auth/PostLoginUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/dailyroutine/GetRoutineDailyThemeListUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/local/GetBearTypeUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/local/GetSignedUpUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/local/InitSIgnUpStateUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/local/InitTokenUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/local/SetBearTypeUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/member/GetHomeUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/member/PatchCottonUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/memberdailyroutine/DeleteDailyRoutineUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/memberdailyroutine/GetDailyRoutineUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/memberdailyroutine/PatchAchieveDailyUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/memberdailyroutine/PostAddDailyRoutineUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/memberhappinessroutine/DeleteMemberHappyRoutineUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/memberhappinessroutine/GetHappyProgressUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/memberhappinessroutine/PatchMemberHappinessAchieveUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/memberhappinessroutine/PostMemberHappyRoutineUseCase.kt
  app/src/main/java/com/sopetit/softie/domain/usecase/version/GetUpdateVersionUseCase.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/complete/DailyRoutineCompleteViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyMyRoutineViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/complete/HappyRoutineCompleteViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/detail/HappyDetailCardViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/login/LoginViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/bearselection/BearSelectionViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/routinechoice/RoutineChoiceViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/splash/SplashActivity.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/splash/SplashViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/splash/UpdateForceDialogFragment.kt
  app/src/main/java/com/sopetit/softie/ui/onboarding/splash/UpdateRecommendDialogFragment.kt
  app/src/main/java/com/sopetit/softie/ui/setting/SettingViewModel.kt
  app/src/main/res/drawable/shape_happyroutineblue_fill_8_rect.xml
  app/src/main/res/layout/dialog_update_force.xml
  app/src/main/res/layout/dialog_update_recommend.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request, Feat, 강희🐬

#152 #151 [qa] 데일리 루틴 2차 qa 이슈 해결
  app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddThemeAdapter.kt
  app/src/main/java/com/sopetit/softie/util/binding/BindingAdapter.kt
  app/src/main/res/layout/fragment_daily_routine.xml
  app/src/main/res/layout/item_daily_routine_add_card.xml
  app/src/main/res/layout/item_daily_routine_add_theme.xml
Labels: QA, 민회🐹

#154 #153[fix] 판다 솜 먹는 로티 파일 수정
  app/src/main/res/raw/panda_eating_daily.json
  app/src/main/res/values/themes.xml
Labels: Pull Request, 강희🐬, fix

#139 #138 [fix] 릴리즈 전 QA 이슈 수정
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyMyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyMyRoutineViewModel.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/delete/HappyDeleteFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/detail/HappyDetailActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/detail/HappyDetailCardPagerAdapter.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListActivity.kt
  app/src/main/java/com/sopetit/softie/util/HorizontalChipItemDecoration.kt
  app/src/main/java/com/sopetit/softie/util/VerticalItemDecoration.kt
  app/src/main/java/com/sopetit/softie/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/ic_happy_card_base.xml
  app/src/main/res/drawable/ic_happy_star_base.xml
  app/src/main/res/layout/activity_happy.xml
  app/src/main/res/layout/activity_happy_add_detail.xml
  app/src/main/res/layout/activity_happy_add_list.xml
  app/src/main/res/layout/fragment_happy_delete.xml
  app/src/main/res/layout/fragment_happy_my_routine.xml
  app/src/main/res/layout/item_happy_add_detail_card.xml
  app/src/main/res/layout/item_happy_add_list.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: UI, 호연🐻‍❄️, fix

#137 #134 [fix] 스낵바 띄우기 및 위치 조정
  app/src/main/java/com/sopetit/softie/ui/happyroutine/HappyMyRoutineFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/delete/HappyDeleteFragment.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/detail/HappyDetailActivity.kt
  app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListActivity.kt
  app/src/main/java/com/sopetit/softie/ui/main/MainActivity.kt
  app/src/main/res/layout/item_happy_add_detail_card.xml
Labels: UI, 호연🐻‍❄️, fix

#159 #158 [hotfix] 행복 루틴 카드 뒷면 visibility 수정
  app/src/main/res/layout/item_happy_add_detail_card.xml
Labels: hotfix🚨, Pull Request, 강희🐬

#161 #160[fix] 곰 미선택시 버튼 비활성화
  app/src/main/java/com/sopetit/softie/ui/onboarding/OnboardingViewModel.kt
  app/src/main/res/layout/fragment_onboarding_bear_selection.xml
  app/src/main/res/values/strings.xml
Labels: UI, 강희🐬, fix
